repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.7  # Use the latest version from https://github.com/astral-sh/ruff-pre-commit/releases
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix, --ignore=E501]
        exclude: '(^|/)playground\.ipynb$'
    -   id: ruff-format