[project]
name = "web-scraping"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.11.12",
    "openpyxl>=3.1.5",
    "playwright>=1.50.0",
    "spacy>=3.8.4",
]
